# Generated by Django 2.0.7 on 2018-08-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='description',
            field=models.CharField(default='enter your text', max_length=1000),
        ),
    ]
