# Generated by Django 2.0.7 on 2018-08-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_language_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
