# Generated by Django 2.0.7 on 2018-08-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_auto_20180801_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
